import Footer from '@/components/footer/footer'
import './globals.css'
import {Road_Rage,Roboto} from 'next/font/google'
import Navbar from '@/components/navbar'
import UpperNavbar from '@/components/uppernavbar'

const roadRage = Road_Rage({
  weight: '400',
  subsets:['latin'],
  display: 'swap'
})
const roboto =Roboto({
  weight:'100',
  subsets: ['latin'],
  display: "swap"
})

export const metadata = {
  title: 'Betting site',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <UpperNavbar/>
        <Navbar roboto={roboto} roadRage={roadRage}/>
        {children}
        <Footer roboto={roboto} roadRage={roadRage} />
      </body>
    </html>
  )
}
